# version of docker compose syntax
version: "3.9"

services:
  app:
    # build in current dir 
    build:
      context: .
      args:
        - DEV=true
    # port mapping
    ports:
      - "8000:8000"
    # map dir local system and docker container
    volumes:
      - ./app:/app
    # command to run the service
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"